### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by AlexMassenzio** [cbouwense/packing-list#1]
this doesnt have the stuff I pack normally. can you change it...?

**Comment by cbouwense** [comment]
Hello Alex Massenzio... Happy Monday!.. : - )

Yes! That feature is on the way... I will keep this open until it is merged..

Warmest regards

**Comment by jfrey-NDCT** [comment]
please keep me posted for any updates as well

Sent from my iPhone with Tapatalk

**Comment by cbouwense** [comment]
Hey team, this has been fixed : - )
